<a href="https://colab.research.google.com/github/RifatMuhtasim/Apache_Spark/blob/main/1.01.PySpark_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gdown
import os
import zipfile

# Replace 'output_path' with the path where you want to save the file
output_path = 'dataset.zip'

if os.path.exists(output_path):
    print("File exists!")

else:
    print("File does not exist.")
    # Replace 'file_id' with the ID of your file in Google Drive
    file_id = '1matQHY1Q4xHT4m_jxVSZ8Oefgk6ZiDi2'
    gdown.download(f'https://drive.google.com/uc?id={file_id}', output_path, quiet=False)

    # Path to your .zip file (Must Change. Same as the Output Path)
    zip_file_path = '/content/dataset.zip'

    # Extract the contents of the .zip file to the root directory
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        zip_ref.extractall('/content/')

    # List the contents of the root directory
    extracted_files = !ls -a /content/
    print("Files extracted to root directory:", extracted_files)

File does not exist.

Downloading...
From: https://drive.google.com/uc?id=1matQHY1Q4xHT4m_jxVSZ8Oefgk6ZiDi2
To: /content/dataset.zip
100%|██████████| 27.5k/27.5k [00:00<00:00, 23.5MB/s]

Files extracted to root directory: ['.  ..  Caste.csv  .config  dataset.zip\tsample_data  test1.csv\ttest2.csv  test3.csv  tips.csv']

In [2]:
#Load Necessary File
import numpy as np
import pandas as pd
import pyspark

In [3]:
#Read dataset with pandas
df = pd.read_csv('test1.csv')
df

        Name  age  Experience  Salary
0      Krish   31          10   30000
1  Sudhanshu   30           8   25000
2      Sunny   29           4   20000
3       Paul   24           3   20000
4     Harsha   21           1   15000
5    Shubham   23           2   18000

# Read dataset with PySpark

In [4]:
#Load SparkSession
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Practice').getOrCreate()
spark

In [7]:
#Read a dataset with pyspark
df_pyspark = spark.read.option("header", "true").csv('test1.csv')
df_pyspark.show()

+---------+---+----------+------+
|     Name|age|Experience|Salary|
+---------+---+----------+------+
|    Krish| 31|        10| 30000|
|Sudhanshu| 30|         8| 25000|
|    Sunny| 29|         4| 20000|
|     Paul| 24|         3| 20000|
|   Harsha| 21|         1| 15000|
|  Shubham| 23|         2| 18000|
+---------+---+----------+------+

In [8]:
#Type of the PySpark
type(df_pyspark)

pyspark.sql.dataframe.DataFrame

In [10]:
#using head
df_pyspark.head(3)

[Row(Name='Krish', age='31', Experience='10', Salary='30000'),
 Row(Name='Sudhanshu', age='30', Experience='8', Salary='25000'),
 Row(Name='Sunny', age='29', Experience='4', Salary='20000')]